# Generated by Django 3.2.13 on 2022-06-28 15:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini', models.SmallIntegerField(help_text='Minibasin identifier. Called cell in HYFAA netcdf file, field mini in geospatial file', unique=True, verbose_name='Minibasin ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'verbose_name': 'Drainage data (mini-sections of river/drainage) by minibasin',
                'db_table': 'geospatial"."drainage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataAssimilated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.SmallIntegerField(help_text='Cell identifier. Called cell in HYFAA netcdf file, field MINI in geospatial file', unique_for_date='date', verbose_name='Minibasin ID')),
                ('date', models.DateField(help_text='Date for the values', verbose_name='Date')),
                ('elevation_mean', models.FloatField(help_text='Water elevation in m. Mean value', null=True)),
                ('flow_mean', models.FloatField(help_text='Stream flow. Mean value', null=True)),
                ('update_time', models.DateTimeField(help_text='Time of last update', null=True)),
                ('is_analysis', models.BooleanField(help_text='Boolean. Whether the value comes from analysis or control series', null=True)),
                ('elevation_median', models.FloatField(help_text='Water elevation in m. Median value', null=True)),
                ('elevation_stddev', models.FloatField(help_text='Water elevation in m. Standard deviation', null=True)),
                ('elevation_mad', models.FloatField(help_text='Water elevation in m. Median absolute deviation', null=True)),
                ('flow_median', models.FloatField(help_text='Stream flow. Median value', null=True)),
                ('flow_stddev', models.FloatField(help_text='Stream flow. Standard deviation', null=True)),
                ('flow_mad', models.FloatField(help_text='Stream flow. Median absolute  deviation', null=True)),
                ('flow_expected', models.FloatField(help_text='Expected value. Calculated using a floating median, over the flow_median values taken on the day surrounding the current day (+ or - 10 days around), during the previous years', null=True)),
                ('flow_anomaly', models.FloatField(help_text='Represents the anomaly compared to expected data. Formula is 100 * (anomaly - expected) / expected', null=True)),
            ],
            options={
                'verbose_name': 'MGB hydrological data, calculated using HYFAA scheduler, with assimilation',
                'db_table': 'hyfaa"."data_assimilated',
            },
        ),
        migrations.CreateModel(
            name='DataForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.SmallIntegerField(help_text='Cell identifier. Called cell in HYFAA netcdf file, field MINI in geospatial file', unique_for_date='date', verbose_name='Minibasin ID')),
                ('date', models.DateField(help_text='Date for the values', verbose_name='Date')),
                ('elevation_mean', models.FloatField(help_text='Water elevation in m. Mean value', null=True)),
                ('flow_mean', models.FloatField(help_text='Stream flow. Mean value', null=True)),
                ('update_time', models.DateTimeField(help_text='Time of last update', null=True)),
                ('is_analysis', models.BooleanField(help_text='Boolean. Whether the value comes from analysis or control series', null=True)),
                ('elevation_median', models.FloatField(help_text='Water elevation in m. Median value', null=True)),
                ('elevation_stddev', models.FloatField(help_text='Water elevation in m. Standard deviation', null=True)),
                ('elevation_mad', models.FloatField(help_text='Water elevation in m. Median absolute deviation', null=True)),
                ('flow_median', models.FloatField(help_text='Stream flow. Median value', null=True)),
                ('flow_stddev', models.FloatField(help_text='Stream flow. Standard deviation', null=True)),
                ('flow_mad', models.FloatField(help_text='Stream flow. Median absolute  deviation', null=True)),
            ],
            options={
                'verbose_name': 'Forecast MGB hydrological data, calculated using HYFAA scheduler, with assimilation',
                'db_table': 'hyfaa"."data_forecast',
            },
        ),
        migrations.CreateModel(
            name='DataMgbStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.SmallIntegerField(help_text='Cell identifier. Called cell in HYFAA netcdf file, field MINI in geospatial file', unique_for_date='date', verbose_name='Minibasin ID')),
                ('date', models.DateField(help_text='Date for the values', verbose_name='Date')),
                ('elevation_mean', models.FloatField(help_text='Water elevation in m. Mean value', null=True)),
                ('flow_mean', models.FloatField(help_text='Stream flow. Mean value', null=True)),
                ('update_time', models.DateTimeField(help_text='Time of last update', null=True)),
                ('is_analysis', models.BooleanField(help_text='Boolean. Whether the value comes from analysis or control series', null=True)),
                ('flow_expected', models.FloatField(help_text='Expected value. Calculated using a floating median, over the flow_median values taken on the day surrounding the current day (+ or - 10 days around), during the previous years', null=True)),
                ('flow_anomaly', models.FloatField(help_text='Represents the anomaly compared to expected data. Formula is 100 * (anomaly - expected) / expected', null=True)),
            ],
            options={
                'verbose_name': 'MGB hydrological data, calculated using HYFAA scheduler, without assimilation',
                'db_table': 'hyfaa"."data_mgbstandard',
            },
        ),
        migrations.CreateModel(
            name='DrainageInclusionMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Inclusion Mask. Only data included in this mask polygons will be displayed. Overrides hyfaa exclusion mask',
                'db_table': 'geospatial_inclusion_mask',
            },
        ),
        migrations.CreateModel(
            name='RainFall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.SmallIntegerField(help_text='Cell identifier. Called cell in HYFAA netcdf file, field MINI in geospatial file', unique_for_date='date', verbose_name='Minibasin ID')),
                ('date', models.DateField(help_text='Date for the values', verbose_name='Date')),
                ('rain', models.FloatField(verbose_name='Rain fall')),
            ],
            options={
                'verbose_name': 'Rainfall data (GSMap for now)',
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('river', models.CharField(blank=True, max_length=50, null=True)),
                ('threshold_drought', models.FloatField(default=-9999, help_text='in m3/s; when no threshold is defined, value is -9999; The values are the low limit of the category', verbose_name='Drought threshold')),
                ('threshold_flood_low', models.FloatField(default=-9999, help_text='in m3/s; when no threshold is defined, value is -9999; The values are the low limit of the category', verbose_name='Flood low threshold')),
                ('threshold_flood_mid', models.FloatField(default=-9999, help_text='in m3/s; when no threshold is defined, value is -9999; The values are the low limit of the category', verbose_name='Flood mid threshold')),
                ('threshold_flood_high', models.FloatField(default=-9999, help_text='in m3/s; when no threshold is defined, value is -9999; The values are the low limit of the category', verbose_name='Flood high threshold')),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('minibasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sagui.drainage', to_field='mini')),
            ],
            options={
                'verbose_name': 'Virtual stations',
            },
        ),
        migrations.AddIndex(
            model_name='rainfall',
            index=models.Index(fields=['-date'], name='sagui_rainf_date_9c20b5_idx'),
        ),
        migrations.AddIndex(
            model_name='rainfall',
            index=models.Index(fields=['cell_id', '-date'], name='sagui_rainf_cell_id_ad0779_idx'),
        ),
        migrations.AddConstraint(
            model_name='rainfall',
            constraint=models.UniqueConstraint(fields=('cell_id', 'date'), name='rainfall_unique_cellid_day'),
        ),
        migrations.AddIndex(
            model_name='drainageinclusionmask',
            index=models.Index(fields=['mask'], name='geospatial__mask_974fff_idx'),
        ),
        migrations.AddIndex(
            model_name='datamgbstandard',
            index=models.Index(fields=['-date'], name='data_mgbsta_date_93ec43_idx'),
        ),
        migrations.AddIndex(
            model_name='datamgbstandard',
            index=models.Index(fields=['cell_id', '-date'], name='data_mgbsta_cell_id_540bca_idx'),
        ),
        migrations.AddConstraint(
            model_name='datamgbstandard',
            constraint=models.UniqueConstraint(fields=('cell_id', 'date'), name='data_mgbstandard_unique_cellid_day'),
        ),
        migrations.AddIndex(
            model_name='dataforecast',
            index=models.Index(fields=['-date'], name='data_foreca_date_10cfa3_idx'),
        ),
        migrations.AddIndex(
            model_name='dataforecast',
            index=models.Index(fields=['cell_id', '-date'], name='data_foreca_cell_id_2b78ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='dataforecast',
            constraint=models.UniqueConstraint(fields=('cell_id', 'date'), name='data_forecast_unique_cellid_day'),
        ),
        migrations.AddIndex(
            model_name='dataassimilated',
            index=models.Index(fields=['-date'], name='data_assimi_date_f1a455_idx'),
        ),
        migrations.AddIndex(
            model_name='dataassimilated',
            index=models.Index(fields=['cell_id', '-date'], name='data_assimi_cell_id_32db20_idx'),
        ),
        migrations.AddConstraint(
            model_name='dataassimilated',
            constraint=models.UniqueConstraint(fields=('cell_id', 'date'), name='data_assimilated_unique_cellid_day'),
        ),
        migrations.AddConstraint(
            model_name='stations',
            constraint=models.UniqueConstraint(fields=('name',), name='stations_name_unique'),
        ),
    ]
