# Generated by Django 4.0.5 on 2022-06-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportState',
            fields=[
                ('tablename', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default='1950-01-01T00:00:00.000Z00', help_text='Datetime of last update from the netcdf data file', verbose_name='Last Updated')),
                ('last_updated_jd', models.FloatField(default=0, help_text='Datetime of last update from the netcdf data file. In CNES Julian days (0 is 01/01/1950)', verbose_name='Last updated in Julian days')),
                ('update_errors', models.SmallIntegerField(default=0, help_text='Nb of errors during update', verbose_name='Update errors')),
                ('last_updated_without_errors', models.DateTimeField(default='1950-01-01T00:00:00.000Z00', help_text='Datetime of last update from the netcdf data file', verbose_name='Last Updated')),
                ('last_updated_without_errors_jd', models.FloatField(default=0, help_text='Datetime of last update from the netcdf data file. In CNES Julian days (0 is 01/01/1950)', verbose_name='Last updated in Julian days')),
            ],
            options={
                'verbose_name': 'Information about the current state of the DB',
                'ordering': ['tablename'],
            },
        ),
    ]
