# Generated by Django 4.0.5 on 2022-06-28 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stations',
            options={'verbose_name': 'Virtual station'},
        ),
        migrations.AlterField(
            model_name='stations',
            name='minibasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sagui.drainage'),
        ),
    ]
