# Generated by Django 4.0.5 on 2022-06-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0002_alter_stations_options_alter_stations_minibasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='drainageinclusionmask',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
