# Generated by Django 4.0.5 on 2022-06-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0002_importstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataassimilated',
            options={'managed': False, 'verbose_name': 'MGB hydrological data, calculated using HYFAA scheduler, with assimilation'},
        ),
        migrations.AlterModelOptions(
            name='dataforecast',
            options={'managed': False, 'verbose_name': 'Forecast MGB hydrological data, calculated using HYFAA scheduler, with assimilation'},
        ),
        migrations.AlterModelOptions(
            name='datamgbstandard',
            options={'managed': False, 'verbose_name': 'MGB hydrological data, calculated using HYFAA scheduler, without assimilation'},
        ),
    ]
