# Generated by Django 4.0.5 on 2022-06-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0002_alter_importstate_tablename'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dataassimilated',
            name='data_assimilated_unique_cellid_day',
        ),
        migrations.RemoveConstraint(
            model_name='dataforecast',
            name='data_forecast_unique_cellid_day',
        ),
        migrations.RemoveConstraint(
            model_name='datamgbstandard',
            name='data_mgbstandard_unique_cellid_day',
        ),
        migrations.RemoveConstraint(
            model_name='stations',
            name='stations_name_unique',
        ),
        migrations.AddConstraint(
            model_name='dataassimilated',
            constraint=models.UniqueConstraint(fields=('cell_id', 'date'), name='hyfaa_data_assimilated_unique_cellid_day'),
        ),
        migrations.AddConstraint(
            model_name='dataforecast',
            constraint=models.UniqueConstraint(fields=('cell_id', 'date'), name='hyfaa_data_forecast_unique_cellid_day'),
        ),
        migrations.AddConstraint(
            model_name='datamgbstandard',
            constraint=models.UniqueConstraint(fields=('cell_id', 'date'), name='hyfaa_data_mgbstandard_unique_cellid_day'),
        ),
        migrations.AddConstraint(
            model_name='stations',
            constraint=models.UniqueConstraint(fields=('name',), name='hyfaa_stations_name_unique'),
        ),
    ]
