# Generated by Django 4.0.5 on 2022-07-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0004_saguiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinibasinsData',
            fields=[
                ('mini', models.SmallIntegerField(help_text='Minibasin identifier. Called cell in HYFAA netcdf file, field mini in geospatial file', primary_key=True, serialize=False, verbose_name='Minibasin ID')),
                ('ordem', models.SmallIntegerField(help_text='Defines the importance of the minibasin. The higher the more important', verbose_name='Ordem')),
                ('sub', models.SmallIntegerField(help_text='Id of parent sub-basin', verbose_name='Sub')),
                ('width', models.FloatField(verbose_name='Width')),
                ('depth', models.FloatField(verbose_name='Depth')),
            ],
            options={
                'verbose_name': 'Data associated to minibasins (for join with drainage or catchment data). Non-geo table as it is now',
                'db_table': 'hyfaa_minibasins_data',
                'ordering': ['mini'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='saguiconfig',
            name='import_max_ordem',
            field=models.SmallIntegerField(default=8, help_text='During import, it is possible to filter based on that value (keep only values where ordem > import_max_ordem. It will improve the import speed, but then max_ordem should not be set below this value, or you might have missing data...', verbose_name='Import max ordem'),
        ),
        migrations.AddIndex(
            model_name='drainage',
            index=models.Index(fields=['mini'], name='hyfaa_drain_mini_a5641f_idx'),
        ),
    ]
