# Generated by Django 4.0.5 on 2022-07-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0006_remove_saguiconfig_import_max_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minibasinsdata',
            options={'ordering': ['mini'], 'verbose_name': 'Data associated to minibasins (for join with drainage or catchment data). Non-geo table as it is now'},
        ),
    ]
