# Generated by Django 4.0.5 on 2022-07-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0008_hyfaa_custom_stats_functions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='minibasinsdata',
            index=models.Index(fields=['mini'], name='hyfaa_minib_mini_9b22ad_idx'),
        ),
        migrations.AddIndex(
            model_name='minibasinsdata',
            index=models.Index(fields=['ordem', 'mini'], name='hyfaa_minib_ordem_c3bf08_idx'),
        ),
        migrations.AddIndex(
            model_name='minibasinsdata',
            index=models.Index(fields=['sub'], name='hyfaa_minib_sub_64a53f_idx'),
        ),
    ]
