# Generated by Django 4.0.5 on 2022-07-05 10:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0014_stations_with_alert_levels_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationsWithAlerts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('river', models.CharField(blank=True, max_length=50, null=True)),
                ('minibasin', models.IntegerField()),
                ('levels', models.JSONField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Stations with alert codes (View)',
                'db_table': 'hyfaa_stations',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
