# Generated by Django 4.0.5 on 2022-07-06 06:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0015_stations_with_previ_levels_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationsWithFlowAlerts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('river', models.CharField(blank=True, max_length=50, null=True)),
                ('minibasin', models.IntegerField()),
                ('levels', models.JSONField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Stations with alert codes (View)',
                'db_table': 'stations_with_flow_alerts',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='saguiconfig',
            name='stations_alert_use_dataset',
            field=models.CharField(choices=[('mgbstandard', 'Mgbstandard'), ('assimilated', 'Assimilated')], default='assimilated', help_text='To determine the alert level for a given stations, its thresholds must be compared with the current values from one dataset. We can choose here which one to use', max_length=15),
        ),
    ]
