# Generated by Django 4.0.5 on 2022-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0017_stationswithflowprevi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationsReferenceFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_year', models.SmallIntegerField()),
                ('station_id', models.SmallIntegerField()),
                ('value', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Stations reference flow values: values from pre-global warming era',
                'db_table': 'stations_reference_flow',
                'ordering': ['day_of_year'],
            },
        ),
        migrations.AddIndex(
            model_name='stationsreferenceflow',
            index=models.Index(fields=['-day_of_year'], name='stations_re_day_of__01573e_idx'),
        ),
        migrations.AddIndex(
            model_name='stationsreferenceflow',
            index=models.Index(fields=['station_id', 'day_of_year'], name='stations_re_station_81db50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stationsreferenceflow',
            unique_together={('day_of_year', 'station_id')},
        ),
    ]
