# Generated by Django 4.0.5 on 2022-07-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0018_stationsreferenceflow_and_more'),
    ]

    operations = [
        migrations.RunSQL(
        """
CREATE OR REPLACE PROCEDURE guyane.create_hyfaa_drainage_geo_view()
    AS
    $$
DECLARE
    dataset_tbl_name text;
    max_ordem integer;
BEGIN
    -- get the name of the dataset to use . Can be default (assimilated) or defined in the saguiconfig table
    SELECT 'guyane.hyfaa_data_with_' || COALESCE((SELECT use_dataset FROM guyane.sagui_saguiconfig LIMIT 1), 'assimilated') || '_aggregate_geo' AS use_dataset
    INTO dataset_tbl_name;
    RAISE INFO 'dataset_tbl_name %', dataset_tbl_name;
    
    SELECT COALESCE(
        (SELECT c.max_ordem FROM guyane.sagui_saguiconfig c LIMIT 1)
        , 12) AS m
    INTO max_ordem;
    RAISE INFO 'max ordem %', max_ordem;
    
    EXECUTE format('CREATE OR REPLACE VIEW  guyane.hyfaa_data_aggregated_geo AS SELECT * FROM %s WHERE ordem >= %s', dataset_tbl_name, max_ordem);
END
$$
LANGUAGE 'plpgsql';

COMMENT ON PROCEDURE guyane.create_hyfaa_drainage_geo_view() IS 'Dynamically created the main view used for VT display of the drainage data. Source data (assim or mgbstandard) and max ordem are taken from the saguiconfig table';

-- execute the procedure and create the guyane.hyfaa_data_aggregated_geo
CALL guyane.create_hyfaa_drainage_geo_view();        
        """),
    ]
