# Generated by Django 4.0.5 on 2022-07-09 09:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0019_hyfaa_data_aggregated_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catchments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini', models.SmallIntegerField(help_text='Minibasin identifier. Called cell in HYFAA netcdf file, field mini in geospatial file', verbose_name='Minibasin ID')),
                ('sub', models.SmallIntegerField(help_text='Subbasin identifier. Subbasin are the level above minibasins', verbose_name='Subbasin ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'verbose_name': 'Drainage data (mini-sections of river/drainage) by minibasin',
                'db_table': 'hyfaa_catchments',
                'ordering': ['mini'],
            },
        ),
        migrations.AddIndex(
            model_name='catchments',
            index=models.Index(fields=['geom'], name='hyfaa_catch_geom_3e720d_idx'),
        ),
        migrations.AddIndex(
            model_name='catchments',
            index=models.Index(fields=['mini'], name='hyfaa_catch_mini_116a1f_idx'),
        ),
    ]
