# Generated by Django 4.0.5 on 2022-07-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0021_rainfall_aggregated_and_mvt'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='catchments',
            constraint=models.UniqueConstraint(fields=('mini',), name='catchments_unique_mini'),
        ),
        migrations.AddConstraint(
            model_name='drainage',
            constraint=models.UniqueConstraint(fields=('mini',), name='drainage_unique_mini'),
        ),
        migrations.AddConstraint(
            model_name='minibasinsdata',
            constraint=models.UniqueConstraint(fields=('mini',), name='minibasins_data_unique_mini'),
        ),
    ]
