# Generated by Django 4.0.5 on 2022-07-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0022_catchments_catchments_unique_mini_and_more'),
    ]

    operations = [
        migrations.RunSQL(
        """
-- Give access only to what is really needed
--GRANT SELECT ON TABLE guyane.drainage_mgb_masked TO tileserv;
GRANT SELECT ON TABLE guyane.hyfaa_drainage TO tileserv;
--GRANT SELECT ON TABLE guyane.hyfaa_data_with_assimilated_aggregate_geo TO tileserv;
--GRANT SELECT ON TABLE guyane.hyfaa_data_with_mgbstandard_aggregate_geo TO tileserv;
GRANT SELECT ON TABLE guyane.hyfaa_data_aggregated_geo TO tileserv;
--GRANT SELECT ON TABLE guyane.stations_with_flow_alerts TO tileserv;
--GRANT SELECT ON TABLE guyane.stations_with_flow_previ TO tileserv;
--GRANT SELECT ON TABLE guyane.rainfall_minibasin_aggregated_geo TO tileserv;
--GRANT SELECT ON TABLE guyane.rainfall_subbasin_aggregated_geo TO tileserv;
GRANT EXECUTE ON FUNCTION guyane.mvt_rainfall TO tileserv;
        """)
    ]
