# Generated by Django 4.0.5 on 2022-11-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0030_update_rainfall_aggregate_mvt'),
    ]

    operations = [
    ]
