# Generated by Django 4.0.5 on 2022-11-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0031_remove_stationsreferenceflow_stations_re_station_81db50_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationsReferenceFlowPeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(default='2010-2020', max_length=20, null=False, unique=True)),
            ],
            options={
                'verbose_name': 'Stations reference flow period: period (years) that can be used for the pre-global warming data series',
                'db_table': 'stations_reference_flow_period',
            },
        ),
        migrations.AlterField(
            model_name='stationsreferenceflow',
            name='period',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sagui.stationsreferenceflowperiod'),
            preserve_default=False,
        ),
    ]
