# Generated by Django 4.0.5 on 2022-11-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0032_stationsreferenceflowperiod_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationsreferenceflow',
            unique_together={('period', 'day_of_year', 'station_id')},
        ),
    ]
