# Generated by Django 4.0.5 on 2022-11-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0033_alter_stationsreferenceflow_unique_together'),
    ]

    operations = [
    ]
