# Generated by Django 4.0.5 on 2022-11-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0033_alter_stationsreferenceflow_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stationsreferenceflow',
            name='stations_re_station_22f930_idx',
        ),
        migrations.RenameField(
            model_name='stationsreferenceflow',
            old_name='station_id',
            new_name='station',
        ),
        migrations.AddIndex(
            model_name='stationsreferenceflow',
            index=models.Index(fields=['station_id', 'day_of_year'], name='stations_re_station_81db50_idx'),
        ),
    ]
