# Generated by Django 4.0.5 on 2023-01-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0035_rename_value_stationsreferenceflow_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmoAlertCategories',
            fields=[
                ('label', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bounds_min', models.FloatField(default=0, help_text='Min value', verbose_name='Min bound')),
                ('bounds_max', models.FloatField(default=0, help_text='Max value', verbose_name='Max bound')),
                ('legend_label', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Categories used for atmospheric data alerts',
                'ordering': ['bounds_min'],
            },
        ),
    ]
