# Generated by Django 4.0.5 on 2023-01-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0036_atmoalertcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmoalertcategories',
            name='alert_label',
            field=models.CharField(help_text='Label for the alert', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atmoalertcategories',
            name='legend_label',
            field=models.CharField(help_text='If provided, replaces min-max for the generation of the legend', max_length=50, null=True),
        ),
    ]
