# Generated by Django 4.0.5 on 2023-01-09 16:40

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0037_atmoalertcategories_alert_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmoalertcategories',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='atmoalertcategories',
            name='alert_label',
            field=models.CharField(blank=True, help_text='Label for the alert', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atmoalertcategories',
            name='legend_label',
            field=models.CharField(blank=True, help_text='If provided, replaces min-max for the generation of the legend', max_length=50, null=True),
        ),
    ]
