# Generated by Django 4.0.5 on 2023-01-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0039_use_ref_data_for_flow_previ_alert_levels'),
    ]

    operations = [
        migrations.RunSQL(
            """
-- obtained with pg_dump -h localhost -p 5432 -U postgres -n guyane -t guyane.stations_reference_flow_period  --data-only --inserts sagui from a pre-fed DB
INSERT INTO guyane.stations_reference_flow_period VALUES 
(1, '2010-2020'),
(2, '2000-2010'),
(3, '1990-2000'),
(4, '1980-1990') 
ON CONFLICT DO NOTHING;

-- obtained with pg_dump -h localhost -p 5432 -U postgres -n guyane -t guyane.sagui_atmoalertcategories  --data-only --inserts sagui from a pre-fed DB
INSERT INTO guyane.sagui_atmoalertcategories VALUES 
('Moyen', 0.4, 0.6, NULL, 'Faible', '#54C372FF'), 
('Bon', -1000, 0.4, '< 0.4', 'Aucune', '#00FFFF89'), 
('Dégradé', 0.6, 0.9, NULL, 'Moyenne', '#FFFF00FF'), 
('Mauvais', 0.9, 1.2, NULL, 'Haute', '#EA4335FF'), 
('Très mauvais', 1.2, 1.5, NULL, 'Très haute', '#980000FF'), 
('Extrêmement mauvais', 1.5, 10000, '> 1.5', 'Critique', '#674EA7FF') 
ON CONFLICT DO NOTHING;
            """),
    ]
