# Generated by Django 4.0.5 on 2023-01-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0040_seed_tables'),
    ]

    operations = [
        migrations.RunSQL(
            """
-- Deals properly with the case where the values can equal to 0 (avoid division by 0 and get consistent result when it occurs)            
            
DROP FUNCTION IF EXISTS guyane.compute_anomaly(double precision, double precision);
CREATE OR REPLACE FUNCTION guyane.compute_anomaly(current_value float, expected_value float)
RETURNS float
AS
$$
BEGIN
    RETURN (
        CASE WHEN current_value + expected_value = 0 THEN '0' ELSE (100 * 2 * (current_value - expected_value) / (current_value + expected_value)) END
        );
   END
$$  LANGUAGE plpgsql;
COMMENT ON FUNCTION guyane.compute_anomaly(current_value float, expected_value float)
    IS 'Anomaly formula. Used to compute flow anomaly';
    """),
    ]
