# Generated by Django 4.0.5 on 2023-02-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0041_fix_anomaly_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmoalertcategories',
            name='label_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atmoalertcategories',
            name='label_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atmoalertcategories',
            name='label_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stationsreferenceflow',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sagui.stationsreferenceflowperiod'),
        ),
        migrations.AlterField(
            model_name='stationsreferenceflow',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sagui.stations'),
        ),
        migrations.AlterField(
            model_name='stationsreferenceflowperiod',
            name='period',
            field=models.CharField(default='2010-2020', max_length=20, unique=True),
        ),
    ]
