# Generated by Django 4.0.5 on 2023-04-25 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0046_atmoalertcategories_alert_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSubscriptions',
            fields=[
                ('email', models.EmailField(help_text="Subscriber's email", max_length=254, primary_key=True, serialize=False)),
                ('stations_forecasts_active', models.BooleanField(default=False, help_text='Activate stations forecast alerts')),
                ('stations_flow_active', models.BooleanField(default=False, help_text='Activate stations flow alerts')),
                ('rain_active', models.BooleanField(default=False, help_text='Activate rain level alerts')),
                ('atmo_active', models.BooleanField(default=False, help_text='Activate atmospheric pollution alerts')),
                ('atmo_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sagui.atmoalertcategories')),
            ],
            options={
                'verbose_name': 'Alert subscription',
            },
        ),
    ]
