# Generated by Django 4.0.5 on 2023-04-25 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0048_alertsubscriptions_stations_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsubscriptions',
            name='rain_level',
            field=models.CharField(choices=[(0, 'n'), (5, 'r1'), (20, 'r2'), (50, 'r3')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertsubscriptions',
            name='atmo_active',
            field=models.BooleanField(default=False, verbose_name='Activate atmospheric pollution alerts'),
        ),
        migrations.AlterField(
            model_name='alertsubscriptions',
            name='atmo_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sagui.atmoalertcategories', verbose_name='Lower threshold to trigger an alert'),
        ),
        migrations.AlterField(
            model_name='alertsubscriptions',
            name='rain_active',
            field=models.BooleanField(default=False, verbose_name='Activate rain level alerts'),
        ),
        migrations.AlterField(
            model_name='alertsubscriptions',
            name='stations_flow_active',
            field=models.BooleanField(default=False, verbose_name='Activate stations flow alerts'),
        ),
        migrations.AlterField(
            model_name='alertsubscriptions',
            name='stations_forecasts_active',
            field=models.BooleanField(default=False, verbose_name='Activate stations forecast alerts'),
        ),
        migrations.AlterField(
            model_name='alertsubscriptions',
            name='stations_watch',
            field=models.ManyToManyField(to='sagui.stations', verbose_name='Stations to watch'),
        ),
    ]
