# Generated by Django 4.0.5 on 2023-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0049_alertsubscriptions_rain_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsubscriptions',
            name='rain_level',
            field=models.CharField(choices=[('0', '0 mm'), ('5', '5 mm'), ('20', '20 mm'), ('50', '50 mm')], default='0', max_length=20),
        ),
    ]
