# Generated by Django 4.0.5 on 2023-04-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagui', '0050_alter_alertsubscriptions_rain_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsubscriptions',
            name='rain_level',
            field=models.CharField(blank=True, choices=[('0', '0 mm'), ('5', '5 mm'), ('20', '20 mm'), ('50', '50 mm')], default='0', max_length=20, null=True, verbose_name='Lower threshold to trigger an alert'),
        ),
        migrations.AlterField(
            model_name='alertsubscriptions',
            name='stations_watch',
            field=models.ManyToManyField(blank=True, null=True, to='sagui.stations', verbose_name='Stations to watch'),
        ),
    ]
